services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    user: "1000:1000"
    init: true
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
