services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    init: true
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
